from . import hr_department
from . import sage_actividad
from . import sage_subactividad
from . import sage_sector
from . import sage_categoria_cliente
from . import sage_tipo_cliente
from . import sage_colectivo
from . import sage_zona
from . import sage_delegacion
from . import sage_territorio
from . import sage_grupo_comercial
from . import res_partner
from . import sale_order 