# -*- coding: utf-8 -*-
from . import account_invoice
from . import crm_lead
from . import crm_team
from . import product_pricelist
from . import res_partner_arelux
from . import res_partner_todocesped
from . import res_partner
from . import res_partner_reason_buy
from . import res_partner_reason_install
from . import res_partner_specific_segment
from . import res_partner_stock_capacity
from . import res_partner_type_surface
from . import res_partner_type_customer_sale
from . import res_partner_contact_form
from . import res_partner_valuation_thing
from . import res_partner_qualification_product
from . import res_partner_reason_buy
from . import sale_order
from . import sale_order_template
from . import shipping_expedition
from . import stock_picking
from . import mail_template
from . import mail_compose_message